name: laypa
channels:
  # - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - numpy<1.24
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.7
  - opencv
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - tensorboard
  - flask
  - pip:
    - 'git+https://github.com/facebookresearch/detectron2.git'
    - timm
    - natsort
    - torch-tb-profiler
    - imagesize