name: laypa
channels:
  # - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - numpy<1.24
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.7
  - opencv
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - flask
  - prometheus_client
  - imagesize
  - pip:
    - 'git+https://github.com/facebookresearch/detectron2.git'
    - 'git+https://github.com/cocodataset/panopticapi.git'
    - ./models/pixel_decoder/ops/
    - natsort
    - distinctipy
