_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  MODE: region

  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 7

  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_region_train",)
  TEST: ("pagexml_region_val",)
DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: choice
  MIN_SIZE_TRAIN: (832, 896, 960, 1024)
  MAX_SIZE_TRAIN: 2048
  RANDOM_FLIP: both

  # FIXME Have the Min size adjustable
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048

  FORMAT: RGB

TRAIN:
  WEIGHTS:

TEST:
  EVAL_PERIOD: 10000
  WEIGHTS: output/RUN_(2022-10-20|16:19:13)/checkpoints/model_best_mIOU.pth

SOLVER:
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.02
  STEPS: (80000, 120000, 160000)
  MAX_ITER: 250000
  

OUTPUT_DIR: ./output