_BASE_: base_segmentation.yaml
MODEL:
  MODE: baseline

  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_baseline_train",)
  TEST: ("pagexml_baseline_val",)

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: ./output/run2-baseline/model_final.pth