_BASE_: base_segmentation.yaml

OUTPUT_DIR: ./output/baseline

MODEL:
  MODE: baseline

  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_baseline_train",)
  TEST: ("pagexml_baseline_val",)

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: pretrained_models/baseline_model_best_mIoU.pth