_BASE_: base_segmentation.yaml
MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_region_train",)
  TEST: ("pagexml_region_val",)

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: /home/stefan/Downloads/output/RUN_(2022-10-31|15:03:11)/checkpoints/model_best_mIOU.pth
