_BASE_: base_segmentation.yaml
MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_region_train",)
  TEST: ("pagexml_region_val",)

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: 