_BASE_: base_segmentation.yaml

OUTPUT_DIR: ./output/region

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  
  WEIGHTS: 
DATASETS:
  TRAIN: ("pagexml_region_train",)
  TEST: ("pagexml_region_val",)

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: /home/stefan/Downloads/layout-analysis/region/RUN_(2022-11-06|03:22:37)_imagenet_freeze/checkpoints/model_best_mIoU.pth

