_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE: 
    FREEZE_AT: 0
  RESUME: false

DATASETS:
  TRAIN: ("train",)
  TEST: ("val",)

DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: choice
  MIN_SIZE_TRAIN: (832, 896, 960, 1024)
  MAX_SIZE_TRAIN: 2048

  # FIXME Have the Min size adjustable
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048

  FORMAT: RGB

  GRAYSCALE:
    PROBABILITY: 0.

  BRIGHTNESS:
    PROBABILITY: 0.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 0.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5
  
  SATURATION:
    PROBABILITY: 0.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  GAUSSIAN_FILTER:
    PROBABILITY: 0.
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 0.5
  
  VERTICAL_FLIP:
    PROBABILITY: 0.5

  ELASTIC_DEFORMATION:
    PROBABILITY: 0.
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 0.5
      STANDARD_DEVIATION: 0.02
    
    ROTATION:
      PROBABILITY: 0.5
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 0.5
      KAPPA: 20.

    SCALE:
      PROBABILITY: 0.5
      STANDARD_DEVIATION: 0.12
  
TEST:
  EVAL_PERIOD: 10000

SOLVER:
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.02
  STEPS: (80000, 120000, 160000)
  MAX_ITER: 250000
  

OUTPUT_DIR: ./output