_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/top_bottom

PREPROCESS:
  BASELINE:
    LINE_WIDTH: 15

MODEL:
  MODE: top_bottom

  SEM_SEG_HEAD:
    NUM_CLASSES: 3

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
